In [25]:
import geopandas as gpd
import numpy as np
from shapely import wkt

In [ ]:
z = gpd.read_parquet("/opt/earthdata/chipsets-definitions.parquet")
z.explore()

In [11]:
zc = gpd.read_parquet("/opt/earthdata/natural_earth_countries.parquet")
zc.shape

(258, 7)

In [12]:
z

,geometry,SOVEREIGNT,SOV_A3,CONTINENT,REGION_UN,SUBREGION,REGION_WB
0,"MULTIPOLYGON (((117.73807 4.15724, 117.78357 4...",Indonesia,IDN,Asia,Asia,South-Eastern Asia,East Asia & Pacific
1,"MULTIPOLYGON (((117.64405 4.21524, 117.64015 4...",Malaysia,MYS,Asia,Asia,South-Eastern Asia,East Asia & Pacific
2,"MULTIPOLYGON (((-69.49712 -17.62140, -69.47578...",Chile,CHL,South America,Americas,South America,Latin America & Caribbean
3,"POLYGON ((-69.50834 -17.43403, -69.51139 -17.3...",Bolivia,BOL,South America,Americas,South America,Latin America & Caribbean
4,"MULTIPOLYGON (((-69.68390 -17.65604, -69.72904...",Peru,PER,South America,Americas,South America,Latin America & Caribbean
...,...,...,...,...,...,...,...
253,"MULTIPOLYGON (((113.57407 22.16075, 113.57407 ...",China,CH1,Asia,Asia,Eastern Asia,East Asia & Pacific
254,"POLYGON ((123.57561 -12.43678, 123.57504 -12.4...",Australia,AU1,Oceania,Oceania,Australia and New Zealand,East Asia & Pacific
255,"POLYGON ((-79.98640 15.79442, -79.98815 15.794...",Bajo Nuevo Bank (Petrel Is.),BJN,North America,Americas,Caribbean,Latin America & Caribbean
256,"POLYGON ((-78.63687 15.86730, -78.63707 15.862...",Serranilla Bank,SER,North America,Americas,Caribbean,Latin America & Caribbean
257,"POLYGON ((117.75389 15.15008, 117.75186 15.151...",Scarborough Reef,SCR,Asia,Asia,South-Eastern Asia,East Asia & Pacific

In [20]:
from shapely import wkt

geom = z[z.SOVEREIGNT=='Portugal'].geometry.values[0]
geom = list(geom.geoms)[0]

with open("/opt/

In [ ]:
country = 'Portugal'
geom = z[z.SOVEREIGNT=='Portugal'].geometry.values[0]
largest_geom = list(geom.geoms)[np.argmax([gi.area for gi in geom.geoms])]
largest_geom

In [31]:
with open(f"/opt/earthdata/wkts/{country}.wkt", "w") as f:
    wkt.dump(largest_geom, f)